import Head from "next/head";
import SideNavbar from "../components/SideNavbar";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Starter Kit</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/pro.ico" />
      </Head>
      <SideNavbar/>
    
      <h1 className="text-2xl mt-72 font-semibold text-center ">
        Let's Build Something Epic 🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀
      </h1>
    </div>
  );
}
